import { Category, Product } from '../types.js';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-soda-water', name: 'المشروبات الغازية والمياه', icon: 'cup-soda' },
  { id: 'cat-chips-snacks', name: 'الشيبسي والسناكس', icon: 'smile' },
  { id: 'cat-biscuits-sweets', name: 'البسكويت والحلويات', icon: 'cookie' },
  { id: 'cat-rice', name: 'الأرز', icon: 'package' },
  { id: 'cat-sugar', name: 'السكر', icon: 'sparkles' },
  { id: 'cat-oils-ghee', name: 'الزيوت والسمنة', icon: 'droplet' },
  { id: 'cat-pasta', name: 'المكرونة', icon: 'layers' },
  { id: 'cat-canned-food', name: 'المعلبات', icon: 'box' },
  { id: 'cat-sauces', name: 'الصلصات', icon: 'utensils' },
  { id: 'cat-tea-coffee', name: 'الشاي والقهوة', icon: 'coffee' },
  { id: 'cat-dairy', name: 'منتجات الألبان', icon: 'milk' },
  { id: 'cat-diapers', name: 'الحفاضات', icon: 'baby' },
  { id: 'cat-spices', name: 'التوابل والإضافات', icon: 'leaf' },
  { id: 'cat-juices', name: 'العصائر', icon: 'glass-water' },
  { id: 'cat-restaurant-supplies', name: 'مستلزمات المطاعم والكافيهات', icon: 'utensils-crossed' },
  { id: 'cat-halawa', name: 'حلاوة البوادي السادة', icon: 'heart' },
  { id: 'cat-tissues', name: 'المناديل', icon: 'scroll' },
  { id: 'cat-indomie', name: 'الإندومي', icon: 'flame' },
];

export const INITIAL_PRODUCTS: Omit<Product, 'id'>[] = [
  // 🥤 1. المشروبات الغازية والمياه
  {
    name: 'بيبسي كانز',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'بيبسي كانز 330 مل مشروب غازي منعش',
  },
  {
    name: 'بيبسي 300 مل',
    category: 'المشروبات الغازية والمياه',
    price: 7,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'بيبسي زجاجة بلاستيك 300 مل',
  },
  {
    name: 'بيبسي 330 مل',
    category: 'المشروبات الغازية والمياه',
    price: 8.5,
    unit: 'كانز',
    image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'بيبسي حجم 330 مل منعش',
  },
  {
    name: 'بيبسي 600 مل',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'بيبسي زجاجة 600 مل حجم وسط',
  },
  {
    name: 'بيبسي 1 لتر',
    category: 'المشروبات الغازية والمياه',
    price: 14,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'بيبسي عائلي 1 لتر',
  },
  {
    name: 'بيبسي 1.5 لتر',
    category: 'المشروبات الغازية والمياه',
    price: 18,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'بيبسي عائلي 1.5 لتر',
  },
  {
    name: 'بيبسي 2 لتر',
    category: 'المشروبات الغازية والمياه',
    price: 22,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'بيبسي عائلي كبير 2 لتر',
  },
  {
    name: 'بيبسي دايت',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 180,
    description: 'بيبسي دايت خالي من السكر',
  },
  {
    name: 'بيبسي زيرو',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'بيبسي زيرو كالوري طعم غني',
  },
  {
    name: 'سفن أب',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'سفن أب مشروب الليمون المنعش',
  },
  {
    name: 'سفن أب دايت',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 150,
    description: 'سفن أب دايت بنكهة الليمون خفيف',
  },
  {
    name: 'ميرندا برتقال',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 280,
    description: 'ميرندا برتقال طعم الفواكه الغني',
  },
  {
    name: 'ميرندا تفاح',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 240,
    description: 'ميرندا تفاح أخضر لذيذ',
  },
  {
    name: 'كوكاكولا',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'كوكاكولا كانز طعم كلاسيكي',
  },
  {
    name: 'كوكاكولا زيرو',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'كوكاكولا زيرو سكر',
  },
  {
    name: 'سبرايت',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 260,
    description: 'سبرايت ليمون منعش',
  },
  {
    name: 'فانتا',
    category: 'المشروبات الغازية والمياه',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'فانتا برتقال لذيذ',
  },
  {
    name: 'شويبس',
    category: 'المشروبات الغازية والمياه',
    price: 12,
    unit: 'كانز',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'شويبس جولد / رمان / يوسفي',
  },
  {
    name: 'أكوافينا 330 مل',
    category: 'المشروبات الغازية والمياه',
    price: 4.5,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'مياه أكوافينا نقية 330 مل',
  },
  {
    name: 'أكوافينا 600 مل',
    category: 'المشروبات الغازية والمياه',
    price: 6,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 600,
    description: 'مياه أكوافينا نقية 600 مل',
  },
  {
    name: 'أكوافينا 1.5 لتر',
    category: 'المشروبات الغازية والمياه',
    price: 9,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'مياه أكوافينا نقية 1.5 لتر',
  },
  {
    name: 'أكوا ريو',
    category: 'المشروبات الغازية والمياه',
    price: 6,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'مياه أكوا ريو معدنية نقية',
  },
  {
    name: 'مياه معدنية أخرى',
    category: 'المشروبات الغازية والمياه',
    price: 6,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'تشكيلة مياه معدنية متنوعة',
  },

  // 🥔 2. الشيبسي والسناكس
  {
    name: 'شيبسي',
    category: 'الشيبسي والسناكس',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'شيبسي بطاطس طبيعية جميع النكهات',
  },
  {
    name: 'دوريتوس',
    category: 'الشيبسي والسناكس',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'دوريتوس ذرة مقرمشة بجبنة الناتشو والفلفل الحلو',
  },
  {
    name: 'شيتوس',
    category: 'الشيبسي والسناكس',
    price: 7,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'شيتوس مقرمشات جبنة وفلفل حار',
  },
  {
    name: 'تايجر',
    category: 'الشيبسي والسناكس',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'شيبسي تايجر قرمشة مضاعفة ونكهات قوية',
  },
  {
    name: 'زيوو',
    category: 'الشيبسي والسناكس',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'سناكس زيوو مقرمشات خفيفة',
  },
  {
    name: 'فشار',
    category: 'الشيبسي والسناكس',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'فشار بالجبنة والزبدة والكراميل',
  },
  {
    name: 'بسكويت مالح',
    category: 'الشيبسي والسناكس',
    price: 5,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'بسكويت مقرمش مملح خفيف',
  },
  {
    name: 'ويفر',
    category: 'الشيبسي والسناكس',
    price: 5,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'ويفر هش ومقرمش محشو بالكريمة',
  },
  {
    name: 'أصناف 5 جنيه',
    category: 'الشيبسي والسناكس',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 600,
    description: 'تشكيلة سناكس وشيبسي فئة 5 جنيه',
  },
  {
    name: 'أصناف 10 جنيه',
    category: 'الشيبسي والسناكس',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 600,
    description: 'تشكيلة شيبسي وسناكس فئة 10 جنيه',
  },
  {
    name: 'أصناف 15 جنيه',
    category: 'الشيبسي والسناكس',
    price: 15,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'شيبسي عائلي كبير فئة 15 جنيه',
  },
  {
    name: 'كراتين مشكلة',
    category: 'الشيبسي والسناكس',
    price: 120,
    unit: 'كرتونة',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 100,
    description: 'كرتونة مشكلة أصناف شيبسي وسناكس متنوعة للمحلات',
  },

  // 🍪 3. البسكويت والحلويات
  {
    name: 'بسكويت سادة',
    category: 'البسكويت والحلويات',
    price: 5,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'بسكويت شاي سادة فاخر',
  },
  {
    name: 'بسكويت ويفر',
    category: 'البسكويت والحلويات',
    price: 5,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'بسكويت ويفر مقرمش بنكهات الشوكولاتة والفانيليا',
  },
  {
    name: 'بسكويت شوكولاتة',
    category: 'البسكويت والحلويات',
    price: 7,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'بسكويت مغطى بالشوكولاتة اللذيذة',
  },
  {
    name: 'بسكويت محشو',
    category: 'البسكويت والحلويات',
    price: 6,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'بسكويت ساندوتش محشو كريمة',
  },
  {
    name: 'كيك',
    category: 'البسكويت والحلويات',
    price: 5,
    unit: 'قطعة',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'كيك إسفنجي هش محشو ومغطى بالكاكاو',
  },
  {
    name: 'رول',
    category: 'البسكويت والحلويات',
    price: 5,
    unit: 'قطعة',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'سويسرول محشو بالكريمة والفراولة',
  },
  {
    name: 'كرواسون',
    category: 'البسكويت والحلويات',
    price: 7,
    unit: 'قطعة',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'كرواسون مورق محشو شوكولاتة أو جبنة',
  },
  {
    name: 'تورتة صغيرة',
    category: 'البسكويت والحلويات',
    price: 15,
    unit: 'قطعة',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 150,
    description: 'تورتة ميني مميزة للتحلية',
  },
  {
    name: 'شيكولاتة',
    category: 'البسكويت والحلويات',
    price: 10,
    unit: 'بار',
    image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'شوكولاتة حليب وبندق فاخرة',
  },
  {
    name: 'لبان',
    category: 'البسكويت والحلويات',
    price: 2,
    unit: 'شريط',
    image: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'لبان نعناع وفواكه منعش',
  },
  {
    name: 'توفي',
    category: 'البسكويت والحلويات',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'توفي كراميل وحليب طري ولذيذ',
  },
  {
    name: 'بونبون',
    category: 'البسكويت والحلويات',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'بونبون فواكه مشكلة ملونة',
  },
  {
    name: 'مصاصات',
    category: 'البسكويت والحلويات',
    price: 2.5,
    unit: 'قطعة',
    image: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 600,
    description: 'مصاصات فواكه بنكهات محببة للأطفال',
  },
  {
    name: 'جيلي',
    category: 'البسكويت والحلويات',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'جيلي كاندي مطاطي بنكهات الفراولة والتوت',
  },
  {
    name: 'مارشميلو',
    category: 'البسكويت والحلويات',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'مارشميلو طري وخفيف ألوان مبهجة',
  },

  // 🍚 4. الأرز
  {
    name: 'أرز معبأ',
    category: 'الأرز',
    price: 32,
    unit: 'كجم',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 800,
    description: 'أرز مصري درجة أولى عالي الجودة معبأ ومعقم',
  },
  {
    name: 'أرز سايب',
    category: 'الأرز',
    price: 28,
    unit: 'كجم',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 1200,
    description: 'أرز مصري سايب ناصع البياض حبة عريضة',
  },

  // 🧂 5. السكر
  {
    name: 'سكر 1 كجم',
    category: 'السكر',
    price: 35,
    unit: 'كيس 1 كجم',
    image: 'https://images.unsplash.com/photo-1581447109200-bf2769116351?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 900,
    description: 'سكر أبيض نقي معبأ كيس 1 كجم',
  },
  {
    name: 'سكر مكعبات',
    category: 'السكر',
    price: 45,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1581447109200-bf2769116351?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'سكر مكعبات فاخر للمشروبات والضيافة',
  },
  {
    name: 'سكر بودرة',
    category: 'السكر',
    price: 40,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1581447109200-bf2769116351?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'سكر بودرة ناعم للحلويات والمخبوزات',
  },

  // 🫗 6. الزيوت والسمنة
  {
    name: 'زيت 1 لتر',
    category: 'الزيوت والسمنة',
    price: 65,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'زيت نباتي نقي للقلي والطبخ 1 لتر',
  },
  {
    name: 'زيت 1.5 لتر',
    category: 'الزيوت والسمنة',
    price: 95,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'زيت نباتي نقي عبوة اقتصادية 1.5 لتر',
  },
  {
    name: 'زيت 2.25 لتر',
    category: 'الزيوت والسمنة',
    price: 140,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'زيت خليط نقي حجم عائلي 2.25 لتر',
  },
  {
    name: 'زيت 3 لتر',
    category: 'الزيوت والسمنة',
    price: 185,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'زيت ذرة / عباد عائلي كبير 3 لتر',
  },
  {
    name: 'زيت 5 لتر',
    category: 'الزيوت والسمنة',
    price: 295,
    unit: 'جردل',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 150,
    description: 'زيت طعام حجم جامبو 5 لتر للمطاعم والاستهلاك الكبير',
  },
  {
    name: 'سمنة بلدي',
    category: 'الزيوت والسمنة',
    price: 220,
    unit: 'كجم',
    image: 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 180,
    description: 'سمنة بلدي طبيعية 100% بنكهة ورائحة مميزة',
  },

  // 🍝 7. المكرونة
  {
    name: 'مكرونة قلم',
    category: 'المكرونة',
    price: 12,
    unit: 'كيس 400 جم',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 600,
    description: 'مكرونة فرن قلم عالية الجودة',
  },
  {
    name: 'مكرونة اسباجيتي',
    category: 'المكرونة',
    price: 12,
    unit: 'كيس 400 جم',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'مكرونة اسباجيتي طويلة ممتازة',
  },
  {
    name: 'مكرونة خواتم',
    category: 'المكرونة',
    price: 12,
    unit: 'كيس 400 جم',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'مكرونة خواتم صغيرة للصلصة والشوربة',
  },
  {
    name: 'مكرونة مرمرية',
    category: 'المكرونة',
    price: 12,
    unit: 'كيس 400 جم',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'مكرونة مرمرية صغيرة للتحمير والكشري',
  },
  {
    name: 'مكرونة لسان عصفور',
    category: 'المكرونة',
    price: 12,
    unit: 'كيس 400 جم',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'لسان عصفور ذهبي للشوربة',
  },
  {
    name: 'مكرونة شعرية',
    category: 'المكرونة',
    price: 12,
    unit: 'كيس 400 جم',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'شعرية ممتازة للأرز والحلويات',
  },
  {
    name: 'مكرونة 350 جم',
    category: 'المكرونة',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'مكرونة عبوة 350 جم اقتصادية',
  },
  {
    name: 'مكرونة 400 جم',
    category: 'المكرونة',
    price: 12,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 600,
    description: 'مكرونة عبوة 400 جم قياسية',
  },
  {
    name: 'مكرونة 1 كجم',
    category: 'المكرونة',
    price: 28,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'مكرونة عبوة عائلية 1 كجم',
  },
  {
    name: 'مكرونة 10 كجم',
    category: 'المكرونة',
    price: 260,
    unit: 'شيكارة',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 120,
    description: 'شيكارة مكرونة 10 كجم للمطاعم ومحلات الكشري',
  },

  // 🥫 8. المعلبات
  {
    name: 'تونة مفتتة',
    category: 'المعلبات',
    price: 32,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1534483509719-3feaee7c30da?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'تونة مفتتة بزيت نباتي لذيذة',
  },
  {
    name: 'تونة قطع',
    category: 'المعلبات',
    price: 55,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1534483509719-3feaee7c30da?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'تونة لحم أبيض قطع كاملة فاخرة',
  },
  {
    name: 'فول',
    category: 'المعلبات',
    price: 15,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'فول مدمس سادة وبالخلطة جاهز للأكل',
  },

  // 🥫 9. الصلصات
  {
    name: 'كاتشب',
    category: 'الصلصات',
    price: 25,
    unit: 'زجاجة',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'كاتشب طماطم طبيعية غني ولذيذ',
  },
  {
    name: 'مايونيز',
    category: 'الصلصات',
    price: 28,
    unit: 'برطمان',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'مايونيز كريمي غني للساندوتشات والسلطات',
  },
  {
    name: 'صلصة طماطم',
    category: 'الصلصات',
    price: 15,
    unit: 'برطمان',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'معجون صلصة طماطم مركزة عالية الجودة',
  },
  {
    name: 'صلصة بيتزا',
    category: 'الصلصات',
    price: 22,
    unit: 'برطمان',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'صلصة بيتزا بالأعشاب الإيطالية والريحان',
  },
  {
    name: 'طحينة',
    category: 'الصلصات',
    price: 45,
    unit: 'برطمان',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'طحينة سمسم بيضاء نقية 100%',
  },

  // ☕ 10. الشاي والقهوة
  {
    name: 'شاي',
    category: 'الشاي والقهوة',
    price: 15,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'شاي أسود حبيبات فاخر',
  },
  {
    name: 'شاي ناعم',
    category: 'الشاي والقهوة',
    price: 18,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'شاي ناعم غني وثقيل للمزاج العالي',
  },
  {
    name: 'شاي فتلة',
    category: 'الشاي والقهوة',
    price: 25,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'شاي فتلة أكياس مغلفة سريعة التحضير',
  },
  {
    name: 'شاي أخضر',
    category: 'الشاي والقهوة',
    price: 28,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'شاي أخضر طبيعي بنكهة النعناع والليمون',
  },
  {
    name: 'ليبتون',
    category: 'الشاي والقهوة',
    price: 30,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'شاي ليبتون العلامة الصفراء الأصلي',
  },
  {
    name: 'العروسة',
    category: 'الشاي والقهوة',
    price: 22,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 600,
    description: 'شاي العروسة الشهير طعم ورائحة لا تقاوم',
  },
  {
    name: 'شاي ربيع',
    category: 'الشاي والقهوة',
    price: 35,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'شاي ربيع إكسبريس خلطة ممتازة',
  },
  {
    name: 'قهوة سادة',
    category: 'الشاي والقهوة',
    price: 40,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'بن برازيلي سادة فاتح أو وسط أو غامق',
  },
  {
    name: 'قهوة محوجة',
    category: 'الشاي والقهوة',
    price: 50,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 280,
    description: 'بن محوج بالحبهان والمستكة وجوزة الطيب',
  },
  {
    name: 'نسكافيه',
    category: 'الشاي والقهوة',
    price: 35,
    unit: 'برطمان',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'قهوة سريعة الذوبان نسكافيه كلاسيك',
  },
  {
    name: 'نسكافيه 3×1',
    category: 'الشاي والقهوة',
    price: 6,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 800,
    description: 'نسكافيه 3 في 1 قهوة مع مبيض وسكر',
  },
  {
    name: 'نسكافيه 2×1',
    category: 'الشاي والقهوة',
    price: 5.5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'نسكافيه 2 في 1 بدون سكر',
  },
  {
    name: 'كابتشينو',
    category: 'الشاي والقهوة',
    price: 7.5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'كابتشينو برغوة غنية ونكهات شوكولاتة وبندق',
  },

  // 🥛 11. منتجات الألبان
  {
    name: 'جبنة بيضاء',
    category: 'منتجات الألبان',
    price: 85,
    unit: 'كجم',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'جبنة بيضاء طبيعية براميلي واسطنبولي',
  },
  {
    name: 'جبنة فيتا',
    category: 'منتجات الألبان',
    price: 35,
    unit: 'علبة 500 جم',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'جبنة فيتا نباتي الدهن طرية ولذيذة',
  },
  {
    name: 'جبنة مثلثات',
    category: 'منتجات الألبان',
    price: 25,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'جبنة مثلثات 8 قطع للأطفال والساندوتشات',
  },
  {
    name: 'جبنة شيدر',
    category: 'منتجات الألبان',
    price: 120,
    unit: 'كجم',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 180,
    description: 'جبنة شيدر حمراء وصفراء مستوردة مبشورة وقوالب',
  },
  {
    name: 'جبنة رومي',
    category: 'منتجات الألبان',
    price: 240,
    unit: 'كجم',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'جبنة رومي قديمة وفاخرة طعم معتق',
  },
  {
    name: 'قشطة',
    category: 'منتجات الألبان',
    price: 45,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'قشطة حليب طبيعية طازجة',
  },
  {
    name: 'كريمة',
    category: 'منتجات الألبان',
    price: 50,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 180,
    description: 'كريمة طهي وحلويات خفق ممتازة',
  },
  {
    name: 'لبن بخيره 500 مل',
    category: 'منتجات الألبان',
    price: 20,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'حليب بخيره كامل الدسم معقم 500 مل',
  },
  {
    name: 'لبن بخيره 1 لتر',
    category: 'منتجات الألبان',
    price: 38,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'حليب بخيره كامل الدسم 1 لتر',
  },

  // 🧒 12. الحفاضات
  // بوني
  {
    name: 'حفاضات بوني - مقاس 1',
    category: 'الحفاضات',
    price: 180,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 100,
    description: 'حفاضات بوني حديثي الولادة مقاس 1 امتصاص عالي',
  },
  {
    name: 'حفاضات بوني - مقاس 2',
    category: 'الحفاضات',
    price: 190,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 100,
    description: 'حفاضات بوني مقاس 2 صغير ملمس قطني',
  },
  {
    name: 'حفاضات بوني - مقاس 3',
    category: 'الحفاضات',
    price: 200,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 120,
    description: 'حفاضات بوني مقاس 3 وسط حماية ضد التسريب',
  },
  {
    name: 'حفاضات بوني - مقاس 4',
    category: 'الحفاضات',
    price: 210,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 120,
    description: 'حفاضات بوني مقاس 4 كبير راحة طوال اليوم',
  },
  {
    name: 'حفاضات بوني - مقاس 5',
    category: 'الحفاضات',
    price: 220,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 100,
    description: 'حفاضات بوني مقاس 5 جونيور راحة وأمان',
  },
  {
    name: 'حفاضات بوني - مقاس 6',
    category: 'الحفاضات',
    price: 230,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 90,
    description: 'حفاضات بوني مقاس 6 كبير جداً',
  },

  // بيبي جوي
  {
    name: 'حفاضات بيبي جوي - مقاس 1',
    category: 'الحفاضات',
    price: 210,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 120,
    description: 'حفاضات بيبي جوي مقاس 1 بملمس الحرير',
  },
  {
    name: 'حفاضات بيبي جوي - مقاس 2',
    category: 'الحفاضات',
    price: 220,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 120,
    description: 'حفاضات بيبي جوي مقاس 2 مضغوط بحشوة ماسية',
  },
  {
    name: 'حفاضات بيبي جوي - مقاس 3',
    category: 'الحفاضات',
    price: 235,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 140,
    description: 'حفاضات بيبي جوي مقاس 3 وسط حماية فائقة',
  },
  {
    name: 'حفاضات بيبي جوي - مقاس 4',
    category: 'الحفاضات',
    price: 245,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 140,
    description: 'حفاضات بيبي جوي مقاس 4 كلوت وعادي',
  },
  {
    name: 'حفاضات بيبي جوي - مقاس 5',
    category: 'الحفاضات',
    price: 260,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 110,
    description: 'حفاضات بيبي جوي مقاس 5 كبير جداً',
  },
  {
    name: 'حفاضات بيبي جوي - مقاس 6',
    category: 'الحفاضات',
    price: 270,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 100,
    description: 'حفاضات بيبي جوي مقاس 6 حماية ليلية',
  },

  // مولفيكس
  {
    name: 'حفاضات مولفيكس - مقاس 1',
    category: 'الحفاضات',
    price: 220,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 110,
    description: 'حفاضات مولفيكس بحماية ثلاثية الأبعاد مقاس 1',
  },
  {
    name: 'حفاضات مولفيكس - مقاس 2',
    category: 'الحفاضات',
    price: 230,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 110,
    description: 'حفاضات مولفيكس مقاس 2 خفيف على بشرة الطفل',
  },
  {
    name: 'حفاضات مولفيكس - مقاس 3',
    category: 'الحفاضات',
    price: 245,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 130,
    description: 'حفاضات مولفيكس مقاس 3 وسط حواجز مانعة للتسريب',
  },
  {
    name: 'حفاضات مولفيكس - مقاس 4',
    category: 'الحفاضات',
    price: 255,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 130,
    description: 'حفاضات مولفيكس مقاس 4 ماكسي راحة فائقة',
  },
  {
    name: 'حفاضات مولفيكس - مقاس 5',
    category: 'الحفاضات',
    price: 270,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 100,
    description: 'حفاضات مولفيكس مقاس 5 جونيور',
  },
  {
    name: 'حفاضات مولفيكس - مقاس 6',
    category: 'الحفاضات',
    price: 285,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 90,
    description: 'حفاضات مولفيكس مقاس 6 كبير جداً',
  },

  // بامبرز
  {
    name: 'حفاضات بامبرز - مقاس 1',
    category: 'الحفاضات',
    price: 240,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 110,
    description: 'بامبرز بريميوم كير مقاس 1 نعومة فائقة',
  },
  {
    name: 'حفاضات بامبرز - مقاس 2',
    category: 'الحفاضات',
    price: 250,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 120,
    description: 'بامبرز مقاس 2 صغير حماية وجفاف حتى 12 ساعة',
  },
  {
    name: 'حفاضات بامبرز - مقاس 3',
    category: 'الحفاضات',
    price: 265,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 130,
    description: 'بامبرز بيبي دراي مقاس 3 وسط',
  },
  {
    name: 'حفاضات بامبرز - مقاس 4',
    category: 'الحفاضات',
    price: 280,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 130,
    description: 'بامبرز مقاس 4 كلوت وعادي لحرية الحركة',
  },
  {
    name: 'حفاضات بامبرز - مقاس 5',
    category: 'الحفاضات',
    price: 295,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 100,
    description: 'بامبرز مقاس 5 كبير جونيور',
  },
  {
    name: 'حفاضات بامبرز - مقاس 6',
    category: 'الحفاضات',
    price: 310,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 90,
    description: 'بامبرز مقاس 6 كبير جداً أقصى درجات الحماية',
  },

  // 🌿 13. التوابل والإضافات
  {
    name: 'ملح',
    category: 'التوابل والإضافات',
    price: 3,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 800,
    description: 'ملح طعام ناعم ومكرر معالج باليود',
  },
  {
    name: 'يانسون',
    category: 'التوابل والإضافات',
    price: 15,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'يانسون طبيعي نقي 100% للمشروبات الدافئة',
  },

  // 🥤 14. العصائر
  {
    name: 'جهينة عصير',
    category: 'العصائر',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'عصير جهينة نكتار جميع النكهات 200 مل',
  },
  {
    name: 'جهينة لبن',
    category: 'العصائر',
    price: 38,
    unit: 'لتر',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'حليب جهينة طبيعي كامل الدسم 1 لتر',
  },
  {
    name: 'بيتي عصائر',
    category: 'العصائر',
    price: 8.5,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'عصائر بيتي كل يوم طعم الفاكهة الطازجة',
  },
  {
    name: 'عصائر مانجو',
    category: 'العصائر',
    price: 12,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'عصير مانجو طبيعي ثقيل ولذيذ',
  },
  {
    name: 'عصائر برتقال',
    category: 'العصائر',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'عصير برتقال منعش غني بفيتامين سي',
  },
  {
    name: 'عصائر كوكتيل',
    category: 'العصائر',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'عصير فواكه مشكلة كوكتيل طبيعي',
  },
  {
    name: 'عصائر تفاح',
    category: 'العصائر',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'عصير تفاح رائق نقي ومنعش',
  },
  {
    name: 'عصائر جوافة',
    category: 'العصائر',
    price: 10,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'عصير جوافة طبيعي مركز',
  },

  // 🍴 15. مستلزمات المطاعم والكافيهات
  {
    name: 'أكواب',
    category: 'مستلزمات المطاعم والكافيهات',
    price: 35,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'أكواب ورقية وبلاستيك للمشروبات الساخنة والباردة (باكت 50 كوب)',
  },
  {
    name: 'أطباق',
    category: 'مستلزمات المطاعم والكافيهات',
    price: 40,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'أطباق فوم وبلاستيك مقسمة للاستخدام لمرة واحدة',
  },
  {
    name: 'أدوات تقديم',
    category: 'مستلزمات المطاعم والكافيهات',
    price: 55,
    unit: 'طقم',
    image: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 180,
    description: 'ملاعق وشوك وسكاكين مغلفة وشاليموه للمطاعم والكافيهات',
  },

  // 🍯 16. حلاوة البوادي السادة
  {
    name: 'حلاوة البوادي سادة 100 جم',
    category: 'حلاوة البوادي السادة',
    price: 15,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'حلاوة طحينية البوادي سادة عبوة فردية 100 جم',
  },
  {
    name: 'حلاوة البوادي سادة 200 جم',
    category: 'حلاوة البوادي السادة',
    price: 28,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'حلاوة طحينية البوادي سادة فاخرة 200 جم',
  },
  {
    name: 'حلاوة البوادي سادة 250 جم',
    category: 'حلاوة البوادي السادة',
    price: 35,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 300,
    description: 'حلاوة طحينية البوادي سادة ربع كجم',
  },
  {
    name: 'حلاوة البوادي سادة 500 جم',
    category: 'حلاوة البوادي السادة',
    price: 65,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 250,
    description: 'حلاوة طحينية البوادي سادة نصف كجم عائلية',
  },
  {
    name: 'حلاوة البوادي سادة 1 كجم',
    category: 'حلاوة البوادي السادة',
    price: 120,
    unit: 'علبة',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 200,
    description: 'حلاوة طحينية البوادي سادة 1 كجم',
  },
  {
    name: 'حلاوة البوادي سادة 2 كجم',
    category: 'حلاوة البوادي السادة',
    price: 230,
    unit: 'جردل',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 120,
    description: 'حلاوة البوادي سادة جردل 2 كجم للسوبرماركت والحلواني',
  },
  {
    name: 'حلاوة البوادي سادة 5 كجم',
    category: 'حلاوة البوادي السادة',
    price: 550,
    unit: 'جردل',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 80,
    description: 'حلاوة البوادي سادة جردل كبير 5 كجم',
  },

  // 🧻 17. المناديل
  {
    name: 'مناديل جيب',
    category: 'المناديل',
    price: 2.5,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 600,
    description: 'مناديل جيب ورقية ناعمة 3 طبقات',
  },
  {
    name: 'مناديل سحب',
    category: 'المناديل',
    price: 25,
    unit: 'باكت',
    image: 'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'مناديل سحب ناعمة 550 منديل معقمة',
  },

  // 🍜 18. الإندومي
  // إندومي 5 جنيه
  {
    name: 'إندومي 5 جنيه - فراخ',
    category: 'الإندومي',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'نودلز إندومي سريعة التحضير بنكهة الدجاج الشهية',
  },
  {
    name: 'إندومي 5 جنيه - خضار',
    category: 'الإندومي',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'نودلز إندومي سريعة التحضير بنكهة الخضار المشكل',
  },
  {
    name: 'إندومي 5 جنيه - لحمة',
    category: 'الإندومي',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'نودلز إندومي سريعة التحضير بنكهة اللحم المتبل',
  },
  {
    name: 'إندومي 5 جنيه - كاري',
    category: 'الإندومي',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'نودلز إندومي سريعة التحضير بنكهة الكاري الهندي',
  },
  {
    name: 'إندومي 5 جنيه - حار',
    category: 'الإندومي',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'نودلز إندومي سريعة التحضير سبايسي حار ونار',
  },
  {
    name: 'إندومي 5 جنيه - جمبري',
    category: 'الإندومي',
    price: 5,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'نودلز إندومي سريعة التحضير بنكهة الجمبري البحري',
  },

  // إندومي 10 جنيه
  {
    name: 'إندومي 10 جنيه - فراخ',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'نودلز إندومي حجم جامبو بنكهة الفراخ',
  },
  {
    name: 'إندومي 10 جنيه - خضار',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'نودلز إندومي حجم جامبو بنكهة الخضار',
  },
  {
    name: 'إندومي 10 جنيه - لحمة',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'نودلز إندومي حجم جامبو بنكهة اللحم',
  },
  {
    name: 'إندومي 10 جنيه - كاري',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'نودلز إندومي حجم جامبو بنكهة الكاري',
  },
  {
    name: 'إندومي 10 جنيه - حار',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 500,
    description: 'نودلز إندومي حجم جامبو حار جداً',
  },
  {
    name: 'إندومي 10 جنيه - جمبري',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 350,
    description: 'نودلز إندومي حجم جامبو بنكهة الجمبري',
  },
  {
    name: 'إندومي 10 جنيه - تشيكن سبايسي',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'نودلز إندومي تشيكن سبايسي دجاج حار ومقرمش',
  },
  {
    name: 'إندومي 10 جنيه - شطة وليمون',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 450,
    description: 'نودلز إندومي بنكهة الشطة والليمون اللاذعة المنعشة',
  },
  {
    name: 'إندومي 10 جنيه - صويا صوص',
    category: 'الإندومي',
    price: 10,
    unit: 'كيس',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80',
    status: 'open',
    minQty: 1,
    maxQty: null,
    stock: 400,
    description: 'نودلز إندومي المقلية مي جورينج بصلصة الصويا والتوابل الإندونيسية',
  },
];
